# [cache]
# type = "file"
# basepath = "/etc/cache"

[observer]
type = "prometheus"

[[providers]]
name = "osm"
type = "mvt_postgis"
host = "postgres-postgis"
max_connections = 50
port = 5432
database = "gis"
user = "default"
password = "secret"

[observer]
type = "prometheus"

[cache]
type = "file"
basepath = "/etc/cache"

  [[providers.layers]]
  name = "landuse"
  geometry_type = "polygon"
  geometry_fieldname = "geom"
  id_fieldname = "osm_id"
  sql = "SELECT class, osm_id, way_area, z_order, ST_AsMVTGeom(geometry, !BBOX!) AS geom FROM layer_landuse(!BBOX!, !ZOOM!)"

  [[providers.layers]]
  name = "waterway"
  geometry_type = "linestring"
  geometry_fieldname = "geom"
  id_fieldname = "osm_id"
  sql = "SELECT class, osm_id, ST_AsMVTGeom(geometry, !BBOX!) AS geom FROM layer_waterway(!BBOX!, !ZOOM!)"

  [[providers.layers]]
  name = "water"
  geometry_type = "polygon"
  geometry_fieldname = "geom"
  id_fieldname = "osm_id"
  sql = "SELECT osm_id, ST_AsMVTGeom(geometry, !BBOX!) AS geom FROM layer_water(!BBOX!, !ZOOM!)"

  [[providers.layers]]
  name = "aeroway"
  geometry_type = "polygon"
  geometry_fieldname = "geom"
  id_fieldname = "osm_id"
  sql = "SELECT osm_id, ST_AsMVTGeom(geometry, !BBOX!) AS geom, type FROM layer_aeroway(!BBOX!, !ZOOM!)"

  [[providers.layers]]
  name = "road"
  geometry_type = "linestring"
  geometry_fieldname = "geom"
  id_fieldname = "osm_id"
  sql = "SELECT osm_id, ST_AsMVTGeom(geometry, !BBOX!) AS geom, class, z_order, 'is' FROM layer_transportation(!BBOX!, !ZOOM!)"

  [[providers.layers]]
  name = "admin"
  geometry_type = "linestring"
  geometry_fieldname = "geom"
  id_fieldname = "osm_id"
  sql = "SELECT osm_id, ST_AsMVTGeom(geometry, !BBOX!) AS geom, admin_level, maritime, disputed FROM layer_admin(!BBOX!, !ZOOM!)"

  [[providers.layers]]
  name = "country_label"
  geometry_type = "point"
  geometry_fieldname = "geom"
  id_fieldname = "osm_id"
  sql = "SELECT osm_id, ST_AsMVTGeom(geometry, !BBOX!) AS geom, name, name_, scalerank, code FROM layer_country_labels(!BBOX!, !ZOOM!)"

  [[providers.layers]]
  name = "poi_label"
  geometry_type = "point"
  geometry_fieldname = "geom"
  id_fieldname = "osm_id"
  sql = "SELECT osm_id, ST_AsMVTGeom(geometry, !BBOX!) AS geom, localrank, scalerank, maki, name FROM layer_poi_label(!BBOX!, !ZOOM!)"

  [[providers.layers]]
  name = "road_label"
  geometry_type = "linestring"
  geometry_fieldname = "geom"
  id_fieldname = "osm_id"
  sql = "SELECT osm_id, ST_AsMVTGeom(geometry, !BBOX!) AS geom, shield, name, name_, ref, reflen, len FROM layer_transportation_name(!BBOX!, !ZOOM!)"

  [[providers.layers]]
  name = "place_label"
  geometry_type = "point"
  geometry_fieldname = "geom"
  id_fieldname = "osm_id"
  sql = "SELECT osm_id, ST_AsMVTGeom(geometry, !BBOX!) AS geom, ldir, localrank, name, type FROM layer_place_label(!BBOX!, !ZOOM!, !PIXEL_WIDTH!)"

  [[providers.layers]]
  name = "building"
  geometry_type = "polygon"
  geometry_fieldname = "geom"
  id_fieldname = "osm_id"
  sql = "SELECT osm_id, ST_AsMVTGeom(geometry, !BBOX!) AS geom FROM layer_buildings(!BBOX!, !ZOOM!)"

[[maps]]
name = "osm"
attribution = 'Map data Â© <a href="http://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
center = [ -0.2416797, 51.5287718, 14.0 ] # London, UK

  [[maps.layers]]
  provider_layer = "osm.landuse"
  min_zoom = 7
  max_zoom = 14

  [[maps.layers]]
  provider_layer = "osm.waterway"
  min_zoom = 8
  max_zoom = 14

  [[maps.layers]]
  provider_layer = "osm.water"
  min_zoom = 0
  max_zoom = 14

  [[maps.layers]]
  provider_layer = "osm.aeroway"
  min_zoom = 12
  max_zoom = 14

  [[maps.layers]]
  provider_layer = "osm.road"
  min_zoom = 6
  max_zoom = 14

  [[maps.layers]]
  provider_layer = "osm.admin"
  min_zoom = 0
  max_zoom = 14

  [[maps.layers]]
  provider_layer = "osm.country_label"
  min_zoom = 3
  max_zoom = 10

  [[maps.layers]]
  provider_layer = "osm.poi_label"
  min_zoom = 14
  max_zoom = 14

  [[maps.layers]]
  provider_layer = "osm.road_label"
  min_zoom = 11
  max_zoom = 14

  [[maps.layers]]
  provider_layer = "osm.place_label"
  min_zoom = 3
  max_zoom = 14

  [[maps.layers]]
  provider_layer = "osm.building"
  min_zoom = 14
  max_zoom = 14
