# Number of worker processes to spawn.
# Set to 0 to run everything in a single process without clustering.
# Use 'ncpu' to run as many workers as there are CPU units
num_workers: 0

# Log error messages and gracefully restart a worker if v8 reports that it
# uses more heap (note: not RSS) than this many mb.
worker_heap_limit_mb: 250

# Logger info
logging:
  level: trace
#  streams:
#  # Use gelf-stream -> logstash
#  - type: gelf
#    host: logstash1003.eqiad.wmnet
#    port: 12201

# Statsd metrics reporter
metrics:
  #type: info
  #host: localhost
  #port: 8125

services:
  - name: tilerator
    # a relative path or the name of an npm package, if different from name
    module: ../app.js
    # optionally, a version constraint of the npm package
    # version: ^0.4.0
    # per-service config
    conf:
      port: 16534

      # more per-service config settings
      # the location of the spec, defaults to spec.yaml if not specified
      spec: ../spec.template.yaml
      # allow cross-domain requests to the API (default '*')
      cors: '*'
      # to disable use:
      # cors: false
      # to restrict to a particular domain, use:
      # cors: restricted.domain.org
      # content for the CSP headers
      # csp: false  # uncomment this line to disable sending them
      # URL of the outbound proxy to use (complete with protocol)
      # proxy: http://my.proxy.org:8080
      # the list of domains for which not to use the proxy defined above
      # no_proxy_list:
      #   - domain1.com
      #   - domain2.org
      # the list of incoming request headers that can be logged; if left empty,
      # the following headers are allowed: cache-control, content-length,
      # content-type, if-match, user-agent, x-request-id
      # log_header_whitelist:
      #   - cache-control
      #   - content-length
      #   - content-type
      #   - if-match
      #   - user-agent
      #   - x-request-id
      redis: redis://redis

      variables:
        cassandra-pswd: cassandra
        cassandra-servers:
        - $CASSANDRA_HOST
        cassandra-user: cassandra
        osmdb-pswd: $PGPASSWORD
        osmdb-user: $PGUSER
        osmdb-host: $PGHOST
        osmdb-port: $PGPORT

      sources: /etc/opt/sources.docker.yaml

      modules:
      - tilelive-tmstyle
      - "@wikimedia/kartotherian-autogen"
      - "@wikimedia/kartotherian-cassandra"
      - "@wikimedia/kartotherian-layermixer"
      - "@wikimedia/kartotherian-overzoom"
      - "@wikimedia/kartotherian-substantial"
      - "@wikimedia/kartotherian-babel"
      - "@kartotherian/tilelive-tmsource"
      - "@kartotherian/tilelive-vector"

      # If true, do not enable admin interface
      daemonOnly: false

      # If true, runs this instance without processing tiles
      # This could be good for queue management
      uiOnly: false

      # Set different timeout for tile generation in case mapnik get stuck on
      # locked resource while reading Postgres
      tileTimeOut: 90000
